services:
  - type: web
    name: will-it-rain-on-my-vacation
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --timeout 300
    healthCheckPath: /
    autoDeploy: true
